### ISSUE TITLE
Unnecesary INDEX in mysql causes whitelist to fail.

### ISSUE THREAD

**Issue by serpi90** [GotoFinal/AutoIn#11]
USING MySQL Backend
In the table GT_nicknames the column `premium` is set as a UNIQUE index, and this prevents the plugin from adding new users to the table (except for the first one), because they are all added with premium = 0. 
No error is shown, i had to inspect the database to find out why this happened.

This issue may be related to https://github.com/GotoFinal/AutoIn/issues/3

This does not happen when using SQlite3 Backend, where `name` is UNIQUE

**Comment by GotoFinal** [comment]
Oh, thanks... 
I have no idea how can I set this as UNIQUE, I will post update in next few hours.
Thanks and sorry ;)

**Comment by GotoFinal** [comment]
Fixed in 3.0-pre.4 update, use `/ai fix 1` command after update, or just remove table before starting server.
