### ISSUE TITLE
Support for premium players whitelist

### ISSUE THREAD

**Issue by serpi90** [GotoFinal/AutoIn#12]
Is it possible to add a whitelist for premium players? (or to modify the existiing one to work with them?).

Currently i can have:

* An only premium server with the default whitelilst without the plugin.
* A server with a whitelist for non-premium users, but that accepts all premium users. Using the plugin with whitelist enabled, and the server in offline mode. (default whitelist disabled)

Is it possible to have a whitelist that works for premium and non-premium users?

# Example:

## Whitelist

* Bob (premium)
* Mary (non-premium)

## Result

`Bob (premium)` and `Mary (non-premium)` can access the server, but `Lisa (premium)` nor `Bart (non-premium)` can access the server because they are not whitelisted.

**Comment by serpi90** [comment]
It works by setting the server in offline-mode, using the default whitelist (non-premium must be in both whitelists) and disabling FixUUID.

**Comment by GotoFinal** [comment]
I will add additional whitelist that will be more compatible with AutoIn than default one.  
Bukkit/MC just don't know how to handle both premum/legal and cracked accounts in one time.

But CrackedWhiteList must be a separate one, this is how it works, it affect only cracked players so you can allow all premium players but only selected cracked-ones.

**Comment by serpi90** [comment]
It currently works, as i mentioned in the previous comment, but cracked players must be in both whitelists, the default one, and the cracked players one.

But it would be nice if you manage it all with your plugin :)
