### ISSUE TITLE
Support Request: Force players AutoIn

### ISSUE THREAD

**Issue by LuxusDarkangel** [GotoFinal/AutoIn#17]
Can you add an option (or permission) to force a player to automatically log in (like premium users), but not being premium? I want this just as support for FakePlayers (to use BuildCraft, ComputerCraft, and other mods that can't work with AuthMe Reloaded as long as unrestrictions don't work and they need to log in but can't do that)?

**Comment by GotoFinal** [comment]
ok.

**Comment by LuxusDarkangel** [comment]
Wow, thank you so much, you're so fast.
Can you post here when you release the update with this feature?

**Comment by GotoFinal** [comment]
In new 3.0-alpha.1 version (it will be today) I added small change that should add support for AuthMe build-in unrestriction nicknames.

**Comment by GotoFinal** [comment]
Check if it work, if not, create new issue.
