### ISSUE TITLE
Add option to select premium status on join.

### ISSUE THREAD

**Issue by LuxusDarkangel** [GotoFinal/AutoIn#18]
Can you add an option to let everybody join, but if he uses the command /autoin ImPremium (or what you like) then your plugin will authenticate him with mojang servers and let him do auto login, and fake-premium players can join the server too? I mean, everybody joins the server with exception flag first time, and if they use that command, then they will get the premium flag.

**Comment by GotoFinal** [comment]
En then? he join with cracked UUID, if he do anything before typing command, he will lose that EQ, and he must rejoin to start "be premium"

**Comment by LuxusDarkangel** [comment]
If i have the FixedUUID option enabled his UUID won't change.

**Comment by GotoFinal** [comment]
But it should work always ;)

**Comment by LuxusDarkangel** [comment]
What should work always?
I mean, he join with cracked UUID, he types the command, and when he rejoin, as i have the FixedUUID option enabled, he will continue having the cracked UUID and he won't loose anything, and everybody will be able to join the server.

**Comment by GotoFinal** [comment]
I don't want creating any features that force to use any options like that.
I will later think about that feature, but... not now.

**Comment by LuxusDarkangel** [comment]
Well, that's optional, and i think there isn't a better form to let cracked, premium and fake premium players play, i think that's just another reason for offline mode servers to use your plugin.

**Comment by GotoFinal** [comment]
Related to #20
