### ISSUE TITLE
Error logging

### ISSUE THREAD

**Issue by FejminTV** [GotoFinal/AutoIn#2]
I got an error during login. When trying to enter this writing is on the whitelist, and is disabled. Sometimes he writes disconect and during firing are server errors

Errosrs in console:

" Disconnecting com.mojang.authlib.GameProfile@6e14ba48[id=0ce81f97-394f-4657-a838-a678f5db287f,name=FejminTV,properties={textures=[com.mojang.authlib.properties.Property@61a30be6]},legacy=false] (/46.186.33.145:50593): Too fast re-login, try with a little delay."

**Comment by GotoFinal** [comment]
Check if error is still thrown on 3.0-pre.3 , and this is error when player reconnect too fast, so are you sure that this is bug?
