### ISSUE TITLE
Add Exception for all user except someone

### ISSUE THREAD

**Issue by xDefcon** [GotoFinal/AutoIn#20]
I think this is a great feature for this plugin.

**Comment by GotoFinal** [comment]
Included in *3.0-alpha.2* as `Options.Both.Players.NegateExceptions` -> it will negate exception values when adding/getting from database. <br>
So after setting this to true, all current exception players will be no-exception, and all no-exception will be exception <br>
There will be also command to switch exception status of all players in DB
