### ISSUE TITLE
PermissionEX Support

### ISSUE THREAD

**Issue by scifi2000** [GotoFinal/AutoIn#22]
I don't know if this is a bug for me, but AutoIn does not work for me with PEX. Fixing skins is working perfectly, but when a player joins, it returns "Could not pass PlayerJoinEvent to AutoIn" and then errors with PEX. Please do it! :)

**Comment by GotoFinal** [comment]
paste error

**Comment by GotoFinal** [comment]
I will close that tomorrow if I don't get any logs.
