### ISSUE TITLE
Problem with xAuth

### ISSUE THREAD

**Issue by CryXQ** [GotoFinal/AutoIn#24]
For some reason, I have not been able to configure it so that Auto-In would automatically login premium players with xAuth.
I've looked into the configuration of both plugins, and I can't figure out what is wrong. Here is both xAuth and AutoIn configuration files. I'd appreciate your help. Thank you.

Auto-In
http://pastebin.com/S0W1kpzv

xAuth:
http://pastebin.com/B0jDzPJ5

**Comment by GotoFinal** [comment]
There is chance that support for xAuth will be removed, author of it don't understand how AutoIn work and he think that this plugin is impossible to do, so he don't want me to support his plugin.

But tell me what is not working? with your AutoIn settings premium players should need to /register but no need to /login after that.
Also paste logs from server start to first login.

PS: don't ask me how created and working plugin can be impossible to do.

**Comment by CryXQ** [comment]
Thanks for informing. I really hope that you continue supporting his plugin, because I like xAuth.

The problem is that like you said, premium players should only need to /register but not need to /login, but xAuth still requires /login.

Here is logs from server start to first login.
At the end of the log Kride uses /login command.
http://pastebin.com/v1SugkRb

**Comment by CryXQ** [comment]
I think it is better to start using LogIt. Thanks anyway!
