### ISSUE TITLE
serious security issue

### ISSUE THREAD

**Issue by Elioz** [GotoFinal/AutoIn#27]
Hello,

I have security issue in my server,
using spigot 1.8.3 and authme, I have two admins with cracked versions.
it doesn't even ask them to login, I tried it from my IP and I was connected directly without login
only after I set enabledlogin it ask for password, it happend to a player too and he got hacked.

how can i setenabledlogin by default to cracked members?

btw, I didn't found where to replay in spigot so I must ask this question here

Thanks for your help

**Comment by GotoFinal** [comment]
paste your AutoIn configuration and whole logs from server start to some first joins.

**Comment by Elioz** [comment]
configuration
http://pastebin.com/tRGvsj7i

log
http://pastebin.com/awb44G4G

**Comment by GotoFinal** [comment]
you are not using bungee?

And, can you check if problem occurs on clear server? (only AuthMe + AutoIn)
PS: think about fixing your server... more errors than logs and it's creating like 20 tasks per second, that seems be laggy.

**Comment by Elioz** [comment]
The errors you see it's because I didn't updated some plugins to 1.8.3
there is no bungee

which java version you mean is outdated?

**Comment by GotoFinal** [comment]
Version of java should not affect how plugins works, but it can affect performance and security of your server, you seems to be using 1.7 u5 when the newest 7 is u69 or u70
or even you should think about newest java 8.

Make that test on clear server.

**Comment by Elioz** [comment]
The server is hosted, should I ask from them to update the java?

**Comment by GotoFinal** [comment]
yeach, you can, but still, that just my tip, this isn't related to AutoIn problem.

> Make that test on clear server.

**Comment by Elioz** [comment]
I know, 
so there is any option to setenabledlogin by default?

**Comment by GotoFinal** [comment]
make that test, setEnabledLogin should be only additional option for premium players.
Normally cracked players should use /login command, you can try disable sessions, and check if that helps.

**Comment by Elioz** [comment]
What do you mean disable sessions?

**Comment by GotoFinal** [comment]
78 line of your config file, and make that test... I can't help you without that.

**Comment by Elioz** [comment]
ok I did it right now, if I will see anything suspicious I will contact you again

thanks for your help and you time.
