### ISSUE TITLE
Problem: Cannot invoke method protected abstract

### ISSUE THREAD

**Issue by gabboman** [GotoFinal/AutoIn#30]
when a premium player tries to connect I have this error. What should we do?

18:10:10 [SEVERE] Error authenticating gabboman with minecraft.net
java.lang.RuntimeException: Cannot invoke method protected abstract net.md_5.bungee.api.config.ServerInfo net.md_5.bungee.api.AbstractReconnectHandler.getStoredServer(net.md_5.bungee.api.connection.ProxiedPlayer)

**Comment by GotoFinal** [comment]
paste also logs from start, bungee version and more logs near error.

**Comment by GotoFinal** [comment]
no logs...
