### ISSUE TITLE
Timing out, already connected to server with BungeeCord version 3.0-alpha.1 and higher

### ISSUE THREAD

**Issue by ssamjh** [GotoFinal/AutoIn#32]
If you configure sockets with AutoIn for a server with BungeeCord and Spigot it disconnects you.

**Comment by GotoFinal** [comment]
can't reproduce on alpha.3

**Comment by ssamjh** [comment]
I'll see if I can re-produce it.

**Comment by Granik24** [comment]
I have same problem with my server. Lobby server doing 100% CPU usage (8 cores) after server freeze.
There is a server log: http://pastebin.com/Dgkg8Yzg

**Comment by Plukkies** [comment]
I have the same problem.

**Comment by GotoFinal** [comment]
try change `NeedLoginToUseCommands` to false
