### ISSUE TITLE
No-Premium players cant join

### ISSUE THREAD

**Issue by MrPesee** [GotoFinal/AutoIn#35]
Hi.
Some of my no premium players cant join, they said that a message comes up:
The tipical message form minecrfat that makes you restart minecraft, but the
restart minecraft and they cant still join:/

Config:
http://pastebin.com/0F34u0aB
--The mysql config is configurated i just deleted inon the pastebin--

Thanks for your time!

**Comment by GotoFinal** [comment]
https://github.com/GotoFinal/AutoIn/wiki/FAQ#cracked-players-with-premium-nicknames-cant-join-to-my-server
