### ISSUE TITLE
Error when a premium logs in

### ISSUE THREAD

**Issue by SrPeterMC** [GotoFinal/AutoIn#38]
When a player logs in, i have this error on the console:
http://pastebin.com/EXEbKQW6

My config file:
http://pastebin.com/F2QxFicX
(The mysql is filled, i just deleted for safety)

I think the erro is when the log in automati the premium users.

**Comment by GotoFinal** [comment]
paste whole logs from server start to that first login (including this error)  
PS: don't remove some parts of logs because you think that I don't need them...just saying..

**Comment by MrPesee** [comment]
I have changed the plugin to LoginSecurity, authme had too many errors:/

**Comment by GotoFinal** [comment]
maybe you was using AuthMe 5.0 instead of 3.5 (3.5 it's more stable)

**Comment by MrPesee** [comment]
Yep, i was using 5.0 But in 3.5 thay had a error with the stackeable items, so i just installed 5.0new version and was ok, but well i think with out authme we have less problems. Thanks for your time;)

**Comment by GotoFinal** [comment]
https://github.com/GotoFinal/AutoIn/issues/45
