### ISSUE TITLE
Auto-In keep saying "Mojang servers is down, we can't allow new players to join!"

### ISSUE THREAD

**Issue by mob41** [GotoFinal/AutoIn#40]
Excuse me, i have a problem of the plugin. I had installed this plugin in BungeeCord and Spigot Server. They are connected to each other with your plugin's socket.

Here's the config:
BungeeCord's plugin - http://pastebin.com/P95Ysekm
Spigot Server's plugin - http://pastebin.com/enyB08K9

And it keeps saying "Mojang servers is down, we can't allow new players to join!" when I am joining the server.

I am using Debian (Linux). Is it causing problems to the server? I have adjusted the firewall but it doesn't work too.

You can try to join my server... then you will see what happens. Ask me in private. My server hasn't published to the internet. It is better to keep it private. :)

--> Tested solution 1
I set the setting that is about "Server Protection" to disable in BungeeCord. Doesn't work.
--> Tested solution 2
I set the setting that is about "Server Protection" to disable in Spigot. Also doesn't work.

The log of the Spigot server says something strange:
http://pastebin.com/x3QVbSTx

The log of the Bungeecord says something the same in spigot.

Is I did something wrong of the config? I hope you can help me. Thanks.

**Comment by mob41** [comment]
Please... I am very argent to use this plugin for Security.

**Comment by GotoFinal** [comment]
o.O really weird error.  
Are you sure that your system clock is good? (correct time)

Try test AutoIn on localhost.

**Comment by mob41** [comment]
Tried on Windows. But it gave another error...

http://pastebin.com/ci3Erpyt

It doesn't let me in with the reason: Server isn't enable yet! But the server is enabled. And it shows "DONE"

**Comment by mob41** [comment]
I currently stopped use this plugin and now directly use AuthMe to do the server security. Is AuthMe caused the problems? Should I use LoginSecurity, xAuth, etc. for the partner of AutoIn? Thanks.

**Comment by GotoFinal** [comment]
can you paste whole logs from server start to this join problems?

**Comment by mob41** [comment]
Sorry, I am busy now. I will reply you as soon as possible.

**Comment by mob41** [comment]
Fixed. Updated the time zone, time and date. Now everything runs well. Your plugin is great! Go and develop the new features! I would like to join your AutoIn Development.

**Comment by mob41** [comment]
GoToFinal, how to disable the your motd function? I would like you use the AimatedMotd for my server.

**Comment by GotoFinal** [comment]
I don't have any MOTD functions, but animatedMOTD will not work with AutoIn.
And as far as I see, this is impossible to change without some bigger re-making both of plugins.

**Comment by mob41** [comment]
okay

**Comment by chuck4100** [comment]
Hello, I am getting this error aswell, what did you do exactly mob41?

**Comment by mob41** [comment]
Sorry for late reply. You should adjust the time and date settings, or follow the NTP Time Server. The problem is causing because AutoIn can't talk with Mojang's servers as the Time / Timezone is incorrect to the international time.

**Comment by bird0021** [comment]
I have encountered this problem , My friend into my server
display Mojang servers is down, we can't allow new players to join
my  system clock is good ,but i can into server, My friend can not

**Comment by mob41** [comment]
As I used AutoIn half a year ago, AutoIn had a lot of exceptions and bugs after MC 1.8. So that I gave up using AutoIn and wait for OpenAutoIn to come. (AutoIn 4.0).

@bird0021 I probably recommend you to post a new issue about this. Post the logs and is there any exception when player joining and leaving, and the configuration files.
