### ISSUE TITLE
You don't have any auth plugin!

### ISSUE THREAD

**Issue by Krulaks** [GotoFinal/AutoIn#42]
![auth](https://cloud.githubusercontent.com/assets/13303797/8639665/8df37892-28e1-11e5-9158-008a867bdc8c.jpg)

On lobby server I have AutoIn and AuthMe installed. Both plugins works.

**Comment by GotoFinal** [comment]
this info is about Bungee, as AutoIn is trying to find so authplugin on bungee too.
