### ISSUE TITLE
One of my players can't login to the server

### ISSUE THREAD

**Issue by ZeroSanzo** [GotoFinal/AutoIn#43]
The other players can login with no issues.

[15:17:12] [Server thread/INFO]: [AutoIn] PREMIUM Player: Niv222 (f387e3b0-1cbf-399e-8172-64e6ecab832b) [/77.126.68.154] connected to the server.
[15:17:12] [Server thread/INFO]: [AuthMe] Niv222 logged in!
[15:17:12] [Server thread/WARN]: Failed to handle packet for /77.126.68.154:54621
nul.goto. ...\\.. .final..lIIIIlllII: No supported server type/version! Error type: LOW -> "Ignore it if you see it first time or only on first login." error code: 9

**Comment by GotoFinal** [comment]
paste whole logs from server start.

**Comment by ZeroSanzo** [comment]
http://pastebin.com/XmUV449X

**Comment by GotoFinal** [comment]
maybe he have some weird launcher/client, idk and I can't reproduce than on my test server.
`[15:17:12] [Server thread/WARN]: Failed to handle packet for /77.126.68.154:54621`

**Comment by ZeroSanzo** [comment]
Issue is resolved*. Not a problem with AutoIn.

It was because the player was standing in an unloaded chunk (for some reason, it never loaded at all). I just have to change his last login location and its all fixed.
