### ISSUE TITLE
Support for the last AuthMe Reloaded v5

### ISSUE THREAD

**Issue by lucasdidur** [GotoFinal/AutoIn#45]
Hello,

Could you add support for the last version of AuthMe?

**Comment by sgdc3** [comment]
Hello @GotoFinal I'm a member of the authmereloaded team, we are avariable for any help to fix this issue :)

**Comment by sgdc3** [comment]
You should also look at our new api documentation: http://www.xephi.fr/AuthMeReloaded/index.html
