### ISSUE TITLE
Why when I installed this plugin and my inventory are has been cleared??

### ISSUE THREAD

**Issue by SxDanking** [GotoFinal/AutoIn#47]
Why when I installed this plugin and my inventory are has been cleared...
![2015-07-14_21 35 27](https://cloud.githubusercontent.com/assets/13342120/8689028/d2622e8e-2a70-11e5-9c7a-bf16cb09850f.png)

**Comment by GotoFinal** [comment]
you had offline-mode server?

**Comment by SxDanking** [comment]
I got , no problem ,  just UUID Problem
