### ISSUE TITLE
Random NPE

### ISSUE THREAD

**Issue by KodekPL** [GotoFinal/AutoIn#5]
Server was running idle when this error happend. There are no other plugins on the server, only AutoIn running.

Version of AutoIn: AutoIn version 3.0-pre.2 Author: GotoFinal

Version of Spigot: CraftBukkit version git-Spigot-c46583f-e6f9fd4 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

Plugin configuration: http://pastebin.com/F7Rwi3aR
StackTrace: http://pastebin.com/jiuUchhd

Pozdrawiam!

**Comment by GotoFinal** [comment]
Check if error is still thrown on 3.0-pre.3 (it will be uploaded today)
