### ISSUE TITLE
Sockets question...

### ISSUE THREAD

**Issue by xwest1** [GotoFinal/AutoIn#51]
When i used shockets, only need install AutoIn in bungeecord or each server?

Example:

What is fine?
1.
BungeeCord AutoIn:
Sockets:
- TYPE: HANDLER
  Enabled: true
  Host: 198.27.76.65
  Port: 24400 # Unique port.

Crack AutoIn: 
Sockets:
- TYPE: LISTENER
  Enabled: true
  Host: 198.27.76.65
  Port: 24400 # This same port as proxy HANDLER
  ServerName: Crack

Or...
2.
BungeeCord AutoIn:
Sockets:
- TYPE: HANDLER
  Enabled: true
  Host: 198.27.76.65
  Port: 24400 # Unique port.

- TYPE: LISTENER
  Enabled: true
  Host: 198.27.76.65
  Port: 24400 # This same port as proxy HANDLER
  ServerName: Crack

**Comment by GotoFinal** [comment]
second example don't have any sense... sockets are for communication, and you connected bungee with itself.

**Comment by xwest1** [comment]
Hi, i am use your plugin, AutoIn, work fine but my bungeecord crash after time.

config of bungeecord
http://pastebin.com/irE2p90r

and config of the spigot server
http://pastebin.com/ZuP2nXMQ

is good? ):
