### ISSUE TITLE
MYSQL Bug

### ISSUE THREAD

**Issue by unlemci** [GotoFinal/AutoIn#52]
When i enable MYSQL in config file its not working and there are so many bug messages on my console.

**Comment by GotoFinal** [comment]
paste them...

**Comment by unlemci** [comment]
Sorry, sorry i retest again and its working.. Thanks for look my comment...

Good work :)

**Comment by unlemci** [comment]
Hello reagain. :)

So how can i use MYSQL with auto-in on bungee server?
