### ISSUE TITLE
MySQL problem

### ISSUE THREAD

**Issue by Granik24** [GotoFinal/AutoIn#53]
Hi there, I have problem with my HUB server.
Sometime, it will freeze with console spamming with this error: http://pastebin.com/Vt2dF9X4

Thanks for help.

**Comment by GotoFinal** [comment]
weird, I have no idea for now, seems that some players are bugged in sql and they exist two times or something like that.

**Comment by Granik24** [comment]
I don't know where is a problem.. What I can do? :/

**Comment by Blackyvk** [comment]
I also found this problem, the player was named Leo_ and the there was another one named leo... i dont know if thats was the problem. will try later when people stop playing.

http://pastebin.com/KYSW4TDj
