### ISSUE TITLE
AuthMeReloaded 5.1 Compatibility

### ISSUE THREAD

**Issue by sgdc3** [GotoFinal/AutoIn#56]
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/tickets/1005-problems-with-auto-in-last-player-location-problem/

Try to use our new API to forcelogin players. Please don't use methods outside of the API!

@GotoFinal

**Comment by GotoFinal** [comment]
I creating new open source version of AutoIn, but currently I have only basic code for detection on 1.8 R3, so it will take some time before I finish it.

PS: In old version I needed use methods outside the API, as it didn't work without them.
AutoIn should force login before any message will be show to client, like "Login now using ./login...."

anyway, Thanks for support :)

**Comment by sgdc3** [comment]
We can add methods to the API if you want :)
