### ISSUE TITLE
forge forwarding support

### ISSUE THREAD

**Issue by hunter688** [GotoFinal/AutoIn#57]
While yours plugin do forwarding, please add support for forge.

See this:

https://github.com/SpigotMC/BungeeCord/pull/1557/files
https://gist.github.com/dualspiral/2eaa52300798d397956d

Thanks a lot.

**Comment by GotoFinal** [comment]
I will not change anything in autoin 3.0, but maybe I will add support for this in autoin 4.0.

But AutoIn isn't for forge anyway, so what is the point?

**Comment by hunter688** [comment]
pls look at supplied urls, its something with ip forwarding...

**Comment by GotoFinal** [comment]
hyym, but actually, as far as I see, AutoIn 3.x use this code.
```
        if (BungeeCord.getInstance().config.isIpForward())
        {
            String newHost = copiedHandshake.getHost() + "\u0000" + this.user.getAddress().getHostString() + "\u0000" + this.user.getUUID();
            final LoginResult profile = this.user.getPendingConnection().getLoginProfile();
            if ((profile != null) && (profile.getProperties() != null) && (profile.getProperties().length > 0))
            {
                newHost = newHost + "\u0000" + BungeeCord.getInstance().gson.toJson(profile.getProperties());
            }

            copiedHandshake.setHost(newHost);
        }
        else if (! this.user.getExtraDataInHandshake().isEmpty())
        {
            copiedHandshake.setHost(copiedHandshake.getHost() + this.user.getExtraDataInHandshake());
        }
```

**Comment by hunter688** [comment]
Will be possible make some branch with forge(sponge) support please?

**Comment by GotoFinal** [comment]
actually, as far as I know sponge have autoin in their ass, and they will remove every thread about it from sponge form.
So I don't want support them.

**Comment by hunter688** [comment]
Ok, release source code. I can fix it for others if don't want.

**Comment by GotoFinal** [comment]
I will not release source code of autoin 3.x.

But AutoIn 4.x will be open sourced, so then you can send a PR with fixed code if anything will be wrong.

**Comment by hunter688** [comment]
Nice news, thanks for information.

**Comment by hunter688** [comment]
Any ETA release of AutoIn 4.x or fix my issue in the 3.x version?

**Comment by hunter688** [comment]
bump

**Comment by hunter688** [comment]
any progress?

**Comment by hunter688** [comment]
Switching to online mode=true solved my issue. No need this plugin now.

**Comment by sgdc3** [comment]
Lol but why did you closed this issue? Keep it open!

**Comment by GotoFinal** [comment]
@sgdc3 I'm not going to support that anyway, this isn't even supported by vanilla bungee cord, so I don't see a reason why my plugin should support it.

**Comment by sgdc3** [comment]
"vanilla bungee cord" what do you mean? Bungeecord supports forge clients.

**Comment by GotoFinal** [comment]
@sgdc3 only without ip forwarding, and this is supported by autoin too, autoin can be also used on cauldron server that use forge without any problems.

**Comment by sgdc3** [comment]
Ah, sorry, I've misunderstood the request ;)
