### ISSUE TITLE
Cache gets corrupted

### ISSUE THREAD

**Issue by galaipa** [GotoFinal/AutoIn#58]
Hi, first of all thanks for this wonderful plugin. I have a problem, and I think it's caused by Autoin. Players lose their inventorys when they travel from one world to another. It only happens sometimes, only when the players get bugged. The funny thing is that the problem is solved if I use the /autoin updateache command. And it's not only with CreativeGates, it also happens with other plugins that teleport the players. It's always ConcurrentModificationException. Could you please give a look to this error? Thanks

CreativeGates error caused by Autoin: http://paste.ubuntu.com/14309365/

**Comment by GotoFinal** [comment]
No AutoIn in logs, so it isn't caused by AutoIn.
Are you using AuthMe 5.x maybe?

**Comment by galaipa** [comment]
Thanks for your reply
I don't use Authme.  The funny thing is that the problem is solved if I use the /autoin updateache command. I have also this errors:  In the first you can read  at nul.goto. ...\\.. .final..lIIIllIlll.abstract(AutoIn_GotoFinal) [AutoIn.jar:?] So it's Autoin

http://paste.ubuntu.com/14310074/

http://paste.ubuntu.com/14310055/

**Comment by GotoFinal** [comment]
This is caused by your plugin ;)

**Comment by galaipa** [comment]
Ok... Thanks for your time and sorry

**Comment by GotoFinal** [comment]
I hope you found issue with your plugin.

io.github.galaipa.GameListener.onJoin(GameListener.java:112)
You are teleporting player using Location object where World is null.
