### ISSUE TITLE
Support UltraAuth

### ISSUE THREAD

**Issue by Small-Ku** [GotoFinal/AutoIn#59]
Hello,
Could you add support for the UltraAuth?
I find that it is very lightweight, and using less resources of server.
Hope you can add support for this plugin.
http://dev.bukkit.org/bukkit-plugins/ultraauth-aa/

**Comment by GotoFinal** [comment]
No, plugins is very small, I don't support small plugins like that.
(I may do, but only if I find really interesting plugin, this is just simple, basic auth plugin)

But author of this plugin may add support for AutoIn.

Also.... no changes will be made to 3.x versions of AutoIn, everything need wait for AutoIn 4.x
