### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by mat41997** [GotoFinal/AutoIn#60]
logs,
http://hastebin.com/jucepurivu.css

no czymaj i naprawiaj : >

**Comment by GotoFinal** [comment]
ale z tego co widzę:
 [AutoIn] [Error] MySQL error, trying reconnect!
to działa, tylko masz skonfigurowane MySQL tak że gubi połączenie jak jest nie używane

**Comment by mat41997** [comment]
ustawienia są domyślne, to wina pukawki : p

**Comment by GotoFinal** [comment]
tak czy siak, pookazuje że się łączy ponownie, więc powinno działać.
