### ISSUE TITLE
There's no AutoIn 4

### ISSUE THREAD

**Issue by MrGregorix** [GotoFinal/AutoIn#62]
I have found critical issue in AutoIn 4, there's no AutoIn 4!
I'm glad to report this issue as first, nobody before had known about this, so to help you I googled a bit and I found some possible solutions:
1. Stop being lazy noob.
2. Stop making Diorite, skprime and north will do the job and you will be able to focus on AutoIn.
3. Stop playing Witcher 3, I can play it for you.
4. Stop making spigot plugins (you said spigot sucks afaik).
5. Make AutoIn 4!
Thanks, this is all.
I sent you some [moniez](https://mrgregorix.net/screenshots/20-45-23.png) to give you a bit motivation you need. You can buy a burger now.
I'm glad I could help! Bye!

**Comment by MrGregorix** [comment]
Will this be fixed?

**Comment by sgdc3** [comment]
...

**Comment by artur9010** [comment]
Nope

**Comment by MrGregorix** [comment]
I'm waiting for an author's response
