### ISSUE TITLE
[[AuthSupportRequest]] BungeeAuth support

### ISSUE THREAD

**Issue by xion87** [GotoFinal/AutoIn#63]
I would like to see addede the support for BungeeAuth plugin (https://www.spigotmc.org/resources/bungeeauth.493/) is a bungee auth plugin that use server as lobby room.
You can find the source here https://github.com/xion87/BungeeAuth (since author got hacked and source was deleted for him), 
For API you can find this here https://github.com/xion87/BungeeAuth/blob/master/Sample%20API%20Script/API%20Script-1.0.php

Thank you!

**Comment by sgdc3** [comment]
What's the issue with it?

**Comment by sgdc3** [comment]
Whoops my android github client messed up how issues and projects are associated. xD
