### ISSUE TITLE
Ban plugins dont work if used without bungeecord.

### ISSUE THREAD

**Issue by Blackyvk** [GotoFinal/AutoIn#64]
I have tried different ban plugins and none of those work if i use auto in.

If I ban a premium player it works, that premium player will never join again.

If I ban a cracked player it kicks the player, but he can log back in... If I ban other player, both players are kicked but they are able to log in again.

BanManager doesnt detect cracked players
AdvancedBans cannot detect the cracked player uuid, is banned by name but still the user can log back in
Skript made Ban "works" the player is banned but can log in and kicked right after.

Only if banned i think essentials works but, i need an sql based ban system.

**Comment by GotoFinal** [comment]
it isn't my issue that some plugins can't support uuids right.

**Comment by Blackyvk** [comment]
is not a ban plugin issue, If i remove the Auto-in plugin i can ban anyone, using online or offline mode.

**Comment by sgdc3** [comment]
No the issue is that every dev has it's own uuid fetching system...

**Comment by GotoFinal** [comment]
@Blackyvk nah... because autoin affects uuids, and not every plugin handle them correctly.

Try run server with online-mode true, and autoin, plugins should think that server is in online mode, so they will use real UUIDs, and hopefully if they aren't created by weird devs: if there is no premium uuid they will use cracked one.
So it should work. (if you don't use fixed-uuid option)

**Comment by Blackyvk** [comment]
well it didnt work, but I tried https://www.spigotmc.org/resources/etriabans.11016/ and seems works well with it... hopefully it doesnt bugs or something, will test it more. I still i think it should be a way to fix other known plugins.

Thanks for your time and the fast reply.

**Comment by GotoFinal** [comment]
@Blackyvk the only way is...
Authors just need fix their plugins... I can't change how other plugins works.
