### ISSUE TITLE
AutoIn Removes permissions!

### ISSUE THREAD

**Issue by Desamax1** [GotoFinal/AutoIn#67]
When i intalled AutoIn plugin (and I made sure I was the server owner), I could not gain accses to /hd help command (using the Holographic Displays plugin). I have no idea why this happend, but when i removed the autoin plugin, i had accses to this command again! Can someone please help me or is this issue permanent?

**Comment by GotoFinal** [comment]
AutoIn don't affect permissions o.O

**Comment by sgdc3** [comment]
Maybe a UUID related issue?

**Comment by Desamax1** [comment]
Hmm, i dont know

**Comment by Desamax1** [comment]
Even if it is, how do i fix it?

**Comment by sgdc3** [comment]
What's your perm manager?

**Comment by Desamax1** [comment]
Essentials Group Manager

**Comment by Desamax1** [comment]
For spigot 1.8

**Comment by sgdc3** [comment]
GroupManager is outdated, and it has tons of UUID related issues, does it store the permissions nickname based or UUID based.

**Comment by Desamax1** [comment]
I think uuid

**Comment by Desamax1** [comment]
I am not sure

**Comment by Desamax1** [comment]
Whatvotherbplugin do you reccomend me?

**Comment by sgdc3** [comment]
PermissionsEx is good enough but the developer support aucks :( Before changing the plugin you should try to delete the current user group files and manually readd your staff to the groups. If you have a rank system based on group permissions then it would be a problem xD

**Comment by GotoFinal** [comment]
You can use AutoIn with "FixedUUIDs" option (it is somewhere in the config), you will lose skins, and all players will use cracked uuids, but most of plugins should work fine. (You should set server to offline mode then)

**Comment by Desamax1** [comment]
@sgdc3 Did you mean delete my groups file or dele my users file? In the gruops there ia not a list of members, only perms, prefix, suffix etc. In the users file howeber, the list goes like this: UUID, Nickname, rank, subrank additional permissions. Should I reset this file after I install AutoIn?

**Comment by Desamax1** [comment]
Or should i completly rewrite my perms/use some other plugin?

**Comment by sgdc3** [comment]
Try to delete your groupmanager USER files (not the groups file)

**Comment by Desamax1** [comment]
Oh., okay. I eill do that and update when im dome

**Comment by Desamax1** [comment]
Done*

**Comment by Desamax1** [comment]
Hi! Sorry for not updating... I was testing with the plugin but the issue is still there.. I have no idea why does this happen. I can only try to use another perms plugin...

**Comment by GotoFinal** [comment]
this is for sure uuid issue, and I can't do anything about it.
Possible solutions:
- Change online-mode of server and bungee (if you use it), that will affect how some plugins see players. so if you have "false" turn it to "true", and if you use true, change it to false.
- Set FixedUUID to true in autoin config and online-mode to false, that will make all players use offline uuids, but that also means that premium players will lose skin etc.

**Comment by Desamax1** [comment]
Hey!
I just tried both of those, but they dont seem to fix the problem... :( I am still missing some permissions even tho my ranks is owner.. I dont know what is the issue......
