### ISSUE TITLE
Inventory and Permissions being removed

### ISSUE THREAD

**Issue by Ninn0x4F** [GotoFinal/AutoIn#68]
Hello, Ive just found about your amazing plugin! As far the tests gone with it, it works fine for some parts. 
My problem is already in the title that the inventory and permissions get's removed on rejoin/restart. 
Plugins installed are: OpenInv, WorldEdit, CoreProtect, Essentials, EssentialsProtect, dynmap, AuthMe, AutoIn
I only have one premium account to test it on (not tested it with cracked).
Settings are default except: Registration is false so premium players don't need to register.
Now to my problems: It's a private server for friends, some of them don't have minecraft and playing as cracked. Your plugin is fixing so much stuff if it would work the way it should. But whenever ive connect to the server my inventory and permissions (op) are gone. Im a normal person spawning on the last position where i logged out. Missing my complete inventory and permissions (op is gone).
I don't know why and can't find it out. No errors in the console. Using spigot 1.9.4 latest revision. 
Hope you can help me out.
Thanks in advance for the answer.

**Comment by GotoFinal** [comment]
Try use other Auth Plugin, like xAuth, LogIt or older version of AuthMe like 3.4, API of 5.x still seems to be buggy....

**Comment by Ninn0x4F** [comment]
I'm having some problems with xAuth same goes for LogIt mostly because of spigot-1.9.4
And yes using an older version of AuthMe 3.4 works but it spitting out some errors in the console.
