### ISSUE TITLE
Bungeecord error

### ISSUE THREAD

**Issue by MiamiCenterPL** [GotoFinal/AutoIn#71]
Hi, I have problem with my Bungeecord server, I have instaled AutoIn plugin, I have this error: http://pastebin.com/8naSSU73 .

 My Bungeecord config: http://pastebin.com/hHtPCg5G

 AutoIn Config (Bungeecord): http://pastebin.com/HuSV34Xn
 AutoIn Config (HUB / Lobby server): http://pastebin.com/rkuwMnvi

 HUB server is running great, I can join this server, but not from Bungeecord ;(

**Comment by Maxetto** [comment]
Since you're using BungeeCord 1.9, you need to use [AutoIn 3.0-alpha.6](https://www.spigotmc.org/resources/auto-in.578/updates).

P.S. I suggest you to check your Bungee Plugins, you have some (such as BungeePortals) that are meant only for Bukkit.

**Comment by MiamiCenterPL** [comment]
I deleted all plugins, I'm using Bungeecord 1.8, and AutoIn 1.7-1.8, still not working...

**Comment by GotoFinal** [comment]
There is no BungeeCord for 1.8, there is BungeeCord for 1.7-1.8 and BungeeCord for 1.8-1.9
all the latest versions of bungeecord need autoin for 1.9

**Comment by MiamiCenterPL** [comment]
Thanks, It's working now <3

**Comment by MiamiCenterPL** [comment]
But I have error "You have connected too fast. You must wait at least 4 seconds between connections"

**Comment by MiamiCenterPL** [comment]
http://pastebin.com/2hVR81xz , All should be right, but I can't join server ;(

**Comment by GotoFinal** [comment]
check new update

**Comment by MiamiCenterPL** [comment]
http://pastebin.com/V4sgjpBy AutoIn alpha 6, http://pastebin.com/Q1wWiKpy AutoIn alpha 7 (It's Spigot error, not Bungeecord)

**Comment by GotoFinal** [comment]
> Ignore it if you see it first time or only on first login.

Try join again, this is some weird error that I can't fix, sometimes happen on first join after starting server.

**Comment by MiamiCenterPL** [comment]
2nd join, error: Internal Exception: io.netty.handler,timeout.ReadTimeoutException, when I uninstal AutoIn, It's all fine, I can just join my server

**Comment by GotoFinal** [comment]
1. Use MySQL
2. paste logs from server start to that error, forum lobby and bungee.

**Comment by MiamiCenterPL** [comment]
http://pastebin.com/wrKWaaUJ , http://pastebin.com/m2XPXN78 . Idk, how to use MySQL, but I will try ;)

**Comment by GotoFinal** [comment]
```
[12:57:46 INFO]: Player _MiamiCenter_ is already invisible!
[12:57:46 INFO]: CONSOLE issued server command: /spawn _MiamiCenter_
[12:57:46 INFO]: Teleportacja...
[12:57:47 ERROR]: Could not find spawn.yml, creating new one...
[12:57:48 INFO]: _MiamiCenter_[/178.37.174.143:8814] logged in with entity id 28 at ([world]0.5, 34.0, 0.5)
[12:57:51 INFO]:
[12:58:21 INFO]: [AuthMe] _MiamiCenter_ registered
```
As far as I see you were able to join.
And what is that empty lime here?

**Comment by MiamiCenterPL** [comment]
When I join, I see Void and server kick me (timeout) this empty line is... I don't know, just empty line...

**Comment by GotoFinal** [comment]
then create test server with AutoIn and AuthMe only, and check if issue is still here.

If you still have this issue, then again, paste logs and configs of autoin

**Comment by MiamiCenterPL** [comment]
On Test Server, same issue... http://pastebin.com/2njGyPEF , http://pastebin.com/kwFMyMyG

**Comment by GotoFinal** [comment]
where is bungee logs, bungee autoin config?

and use localhost for socket configs if bungee and server is on this same host.

Also try update bungee.

**Comment by MiamiCenterPL** [comment]
I changed socket IP's to localhost, again same issue... http://pastebin.com/fqcLLMBw I have latest Bungeecord, It seems like my network is weak, or something... World can't load, server kick me "Timeout" idk...

**Comment by GotoFinal** [comment]
so I don't have more ideas, you can try check that without authme too.

**Comment by MiamiCenterPL** [comment]
Same withouls Authme ;/
