### ISSUE TITLE
Kcauldron login issue

### ISSUE THREAD

**Issue by popcorn9499** [GotoFinal/AutoIn#72]
it logs me out while connecting to a kcauldron server. It is giving me a huge list of errors on the bungeecord too. I am running a forked **[bungeecord](https://github.com/HexagonMC/BungeeCord)** It gives me 1.7 to 1.9. the issue is basically the forge isnt seeming to do the handshake properly over the bungeecord. It works fine by itself but if bungee intercepts with autoin it doesnt work.
[bungee and forge client](https://www.dropbox.com/s/i89aeos7ag1bkqu/2016-05-22%2008_54_21-C__WINDOWS_system32_cmd.exe.png?dl=0)

[the kcauldron console](https://www.dropbox.com/s/67ouy1tu3gcn6ha/2016-05-22%2008_57_14-C__WINDOWS_system32_cmd.exe.png?dl=0)

Those are the errors. i will reproduce this issue in a 1.7 to 1.8 bungeecord if you want me to. but it works perfectly fine with vanila servers. and autoin works fine on the bungeecord by itself

**Comment by popcorn9499** [comment]
i check it and it works fine with a regular bungeecord so idk y the forge packets arent being sent right on the 1.7 to 1.9 bungee

**Comment by GotoFinal** [comment]
KCauldron isn't supported, only normal version was, and I don't have plans to support KCauldron in the future, it is really hard to implement via bukkit side and only like 3 people use it.

Also any edited versions of bungeecord may not work. Sorry :<

**Comment by popcorn9499** [comment]
this one was edited but it was only porting in 1.7
