### ISSUE TITLE
Can't move

### ISSUE THREAD

**Issue by checkplys** [GotoFinal/AutoIn#77]
I have AutoIn 1.9 in my bungeecord and AutoIn 1.8 and ViaVersion in spigot servers, when I join my server I get into the hub, and I can't move, no errors on console, nothing, I just can't move, I already tried disabling all my plugins and let just AutoIn enabled, and still can't move.

**Comment by GotoFinal** [comment]
it may not work with via version, also that issuse may be related to authme if you use it

**Comment by checkplys** [comment]
Like I said, I disabled all plugins and just let AutoIn enabled for test (even ViaVersion and AuthMe where diabled), restarted the server, and I can't move.

**Comment by checkplys** [comment]
I found using other plugins, that it happens when I enable premiumUUID O.o, I tested with other "uuid fix" plugins and it also happens.
